### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by yephny** [Crazy-Marvin/FucksGiven#100]
## :writing_hand: Describe the bug
App crashes upon launch

## :bomb: Steps to reproduce
1. Launch the app

## :iphone: Tech info
- OS: Android 13
- App Version: 1.0.0

**Comment by CrazyMarvin** [comment]
I could reproduce crashes when opening the statistics. Do you mean that or don't you even see the Home screen?

**Comment by pixelcap2** [comment]
it crashes on launch for me as well
doesn't launch at all

**Comment by BokitoInc** [comment]
Same also crashes with the f-droid version or the latest 1.0.2 release from github. Tried the gplaystore (aurora) and that one worked.
LineageOS 20 microg on apollon

**Comment by Nindaleth** [comment]
Hi, I also get a crash immediately on launch without seeing any UI. Version 1.0.0 from F-Droid, Android 13 (Motorola so almost stock Android).

Here's a backtrace that I get, ends with
```
java.lang.NoSuchMethodError: No direct method <init>(Landroid/os/LocaleList;)V in class Landroid/app/LocaleConfig; or its super classes (declaration of 'android.app.LocaleConfig' appears in /system/framework/framework.jar)
at rocks.poopjournal.fucksgiven.MainActivity$onCreate$1.invoke(MainActivity.kt:36)
at rocks.poopjournal.fucksgiven.MainActivity$onCreate$1.invoke(MainActivity.kt:32)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
```

<details><summary>Full backtrace</summary>

```

FATAL EXCEPTION: main
Process: rocks.poopjournal.fucksgiven, PID: 30363
java.lang.NoSuchMethodError: No direct method <init>(Landroid/os/LocaleList;)V in class Landroid/app/LocaleConfig; or its super classes (declaration of 'android.app.LocaleConfig' appears in /system/framework/framework.jar)
at rocks.poopjournal.fucksgiven.MainActivity$onCreate$1.invoke(MainActivity.kt:36)
at rocks.poopjournal.fucksgiven.MainActivity$onCreate$1.invoke(MainActivity.kt:32)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
at androidx.compose.ui.platform.ComposeView.Content(ComposeView.android.kt:428)
at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:252)
at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:251)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:195)
at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:119)
at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:118)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:110)
at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$2.invoke(Wrapper.android.kt:158)
at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$2.invoke(Wrapper.android.kt:157)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:157)
at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:142)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:90)
at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3302)
at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:3235)
at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:725)
at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:1071)
at androidx.compose.runtime.CompositionImpl.composeInitial(Composition.kt:633)
at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:619)
at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:142)
at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:133)
at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:1191)
at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:133)
at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:183)
at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:322)
at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.kt:199)
at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:140)
at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:133)
at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:1266)
at android.view.View.dispatchAttachedToWindow(View.java:21391)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3503)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3510)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3510)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3510)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3510)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3008)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2473)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9300)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
at android.view.Choreographer.doCallbacks(Choreographer.java:899)
at android.view.Choreographer.doFrame(Choreographer.java:832)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
at android.os.Handler.handleCallback(Handler.java:984)
at android.os.Handler.dispatchMessage(Handler.java:104)
at android.os.Looper.loopOnce(Looper.java:238)
at android.os.Looper.loop(Looper.java:357)
at android.app.ActivityThread.main(ActivityThread.java:8094)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:957) 
```
</details>

**Comment by Nindaleth** [comment]
For the record, I've downloaded the 1.0.2 APK from the Releases and it crashes at the same time with the same backtrace.

**Comment by CrazyMarvin** [comment]
> For the record, I've downloaded the 1.0.2 APK from the Releases and it crashes at the same time with the same backtrace.

Thanks for the information.
That gave me an idea.

**Comment by CrazyMarvin** [comment]
@mubeen1519, may you please check if I messed up the [per-app language setup](https://developer.android.com/guide/topics/resources/app-languages)?

I added`generateLocaleConfig = true` in the [build.gradle.kts](https://github.com/Crazy-Marvin/FucksGiven/blob/development/android/app/build.gradle.kts) and created the file [android/app/src/main/res/resources.properties](https://github.com/Crazy-Marvin/FucksGiven/blob/development/android/app/src/main/res/resources.properties).

**Comment by Spiderfffun** [comment]
Same here, lineage android 13

**Comment by CrazyMarvin** [comment]
We will try to find a fix next month.

**Comment by mubeen1519** [comment]
[FucksGiven-1.0.5-debug.zip](https://github.com/user-attachments/files/17257266/FucksGiven-1.0.5-debug.zip)
please test the apk guys and let me know if it still crash

https://github.com/Crazy-Marvin/FucksGiven/pull/116

**Comment by yephny** [comment]
@mubeen1519 It works, no crashes.

**Comment by CrazyMarvin** [comment]
> @mubeen1519 It works, no crashes.

Awesome, thanks for your feedback. 👍
