### ISSUE TITLE
Crash upon making a new rant

### ISSUE THREAD

**Issue by v1s7** [Crazy-Marvin/FucksGiven#124]
## :writing_hand: Describe the bug

The app crashes when you click the plus button
[recorded.log](https://github.com/user-attachments/files/17285274/recorded.log)
## :bomb: Steps to reproduce

1. Launch the app
2. Click on the + button
3. Get sent to your phone's home screen

## :wrench: Expected behavior

The popup menu gets opened as usual

## :iphone: Tech info
- Device:  realme 8 4G
- OS:  13
- App Version:  1.0.5 (from the [Releases](https://github.com/Crazy-Marvin/FucksGiven/releases/tag/v1.0.5))

## :page_facing_up: Additional context

Weird thing is that the issue also appeared when I first installed the app, but when I tried to record its logcat the bug just disappeared and everything worked as intended. So it may not be a surprise if this won't be reproducable.

<details>
<summary>crash report</summary>
FATAL EXCEPTION: main
Process: rocks.poopjournal.fucksgiven, PID: 2419
java.lang.NoSuchMethodError: No static method performImeAction$default(Landroidx/compose/ui/semantics/SemanticsPropertyReceiver;Ljava/lang/String;Lkotlin/jvm/functions/Function0;ILjava/lang/Object;)V in class Landroidx/compose/ui/semantics/SemanticsPropertiesKt; or its super classes (declaration of 'androidx.compose.ui.semantics.SemanticsPropertiesKt' appears in /data/app/~~oeiYhP_Stx6KGU53JjaoUg==/rocks.poopjournal.fucksgiven-wtpkPwG8bPDbZEy1v8DcUA==/base.apk)
	at androidx.compose.foundation.text.CoreTextFieldKt$CoreTextField$semanticsModifier$1.invoke(CoreTextField.kt:532)
	at androidx.compose.foundation.text.CoreTextFieldKt$CoreTextField$semanticsModifier$1.invoke(CoreTextField.kt:433)
	at androidx.compose.ui.semantics.CoreSemanticsModifierNode.applySemantics(SemanticsModifier.kt:73)
	at androidx.compose.ui.node.LayoutNode$collapsedSemantics$1.invoke(LayoutNode.kt:430)
	at androidx.compose.ui.node.LayoutNode$collapsedSemantics$1.invoke(LayoutNode.kt:421)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2303)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:500)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:256)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeSemanticsReads$ui_release(OwnerSnapshotObserver.kt:121)
	at androidx.compose.ui.node.LayoutNode.getCollapsedSemantics$ui_release(LayoutNode.kt:421)
	at androidx.compose.ui.semantics.SemanticsNodeKt.SemanticsNode(SemanticsNode.kt:48)
	at androidx.compose.ui.semantics.SemanticsNode.fillOneLayerOfSemanticsWrappers(SemanticsNode.kt:268)
	at androidx.compose.ui.semantics.SemanticsNode.fillOneLayerOfSemanticsWrappers(SemanticsNode.kt:270)
	at androidx.compose.ui.semantics.SemanticsNode.fillOneLayerOfSemanticsWrappers(SemanticsNode.kt:270)
	at androidx.compose.ui.semantics.SemanticsNode.fillOneLayerOfSemanticsWrappers(SemanticsNode.kt:270)
	at androidx.compose.ui.semantics.SemanticsNode.unmergedChildren$ui_release(SemanticsNode.kt:248)
	at androidx.compose.ui.semantics.SemanticsNode.getChildren(SemanticsNode.kt:327)
	at androidx.compose.ui.semantics.SemanticsNode.getReplacedChildren$ui_release(SemanticsNode.kt:298)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat_androidKt.getAllUncoveredSemanticsNodesToMap$findAllSemanticNodesRecursive(AndroidComposeViewAccessibilityDelegateCompat.android.kt:3665)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat_androidKt.getAllUncoveredSemanticsNodesToMap$findAllSemanticNodesRecursive(AndroidComposeViewAccessibilityDelegateCompat.android.kt:3667)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat_androidKt.getAllUncoveredSemanticsNodesToMap$findAllSemanticNodesRecursive(AndroidComposeViewAccessibilityDelegateCompat.android.kt:3667)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat_androidKt.getAllUncoveredSemanticsNodesToMap$findAllSemanticNodesRecursive(AndroidComposeViewAccessibilityDelegateCompat.android.kt:3667)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat_androidKt.getAllUncoveredSemanticsNodesToMap(AndroidComposeViewAccessibilityDelegateCompat.android.kt:3700)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat_androidKt.access$getAllUncoveredSemanticsNodesToMap(AndroidComposeViewAccessibilityDelegateCompat.android.kt:1)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.getCurrentSemanticsNodes(AndroidComposeViewAccessibilityDelegateCompat.android.kt:342)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.sendAccessibilitySemanticsStructureChangeEvents(AndroidComposeViewAccessibilityDelegateCompat.android.kt:3085)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.checkForSemanticsChanges(AndroidComposeViewAccessibilityDelegateCompat.android.kt:2358)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.semanticsChangeChecker$lambda$46(AndroidComposeViewAccessibilityDelegateCompat.android.kt:2189)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.$r8$lambda$CZAjA4a8ePLF9FU4Ia6Vf_-igrw(Unknown Source:0)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat$$ExternalSyntheticLambda2.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8370)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
</details>

**Comment by garnetbugbee** [comment]
I'm on a galaxy s10e with a locked bootloader running the latest update that the Samsung got in the US. Mine does the exact same thing. This looks like a great application by the way.

**Comment by patienttruth** [comment]
Same thing. Phone is Pixel 6 on latest version of GrapheneOS.

**Comment by woodmaker** [comment]
Same thing. FP5, /e/os 2.3, android 13. When I click on (+), i can see something for a frame or a moment and then home screen.

**Comment by spj2401Dev** [comment]
Same here. On a A55 on Android 14

**Comment by anantone** [comment]
Me too. I thought it was a way to make sure no fucks are given??

**Comment by anantone** [comment]
Works with debug apk from other issue. F droid release is what crashes (giving zero fucks for eva)

**Comment by dinosophos** [comment]
Same here, FP4 with e.os 2.4, F-Droid release 1.05

**Comment by PedroZero** [comment]
Same here on Samsung M54. I really like the app, so I'm hoping it gets fixed soon.
Edit: the debug apk does work indeed. however, an official update would be great.

**Comment by ionlycod** [comment]
Marvin, do u giv a fuc?
plz fixxx

**Comment by CrazyMarvin** [comment]
That's really strange. I don't have an idea yet unfortunately.
Do you see something, @mubeen1519?

**Comment by mubeen1519** [comment]
> That's really strange. I don't have an idea yet unfortunately.
> Do you see something, @mubeen1519?

ah will check the logs to see the problem he might facing i guess thats a rare scenario he faced on the device.

**Comment by CrazyMarvin** [comment]
May you please check if the APK from the [release](https://github.com/Crazy-Marvin/FucksGiven/releases) and [Google Play](https://play.google.com/store/apps/details?id=rocks.poopjournal.fucksgiven) are working?

**Comment by ghost** [comment]
Hey. I'm facing the exact same issue with fdroid release.

- Android 13, lineage os, redmi note 9 pro 5g.

> May you please check if the APK from the [release](https://github.com/Crazy-Marvin/FucksGiven/releases) and [Google Play](https://play.google.com/store/apps/details?id=rocks.poopjournal.fucksgiven) are working?

I checked both github and play store releases, too. Both have the same issue, crashing when + button is clicked.

**Comment by chenshuiluke** [comment]
I'm having the same issue with my s23 ultra:


https://github.com/user-attachments/assets/9de44878-6b28-4066-8d96-b669a8cd6c33

**Comment by CrazyMarvin** [comment]
I don't have a solution unfortunately. 🙈

**Comment by ionlycod** [comment]
Version 1.0.2 did not have this problem.

**Comment by zekooooo** [comment]
Exact same situation for me, Android 14 on Sony Xperia. Just tried 1.0.2 and it works fine, thanks for the tip @ionlycod

**Comment by JD-The-65th** [comment]
Same on my S21 and S24. I literally can't give a fuck.

**Comment by CrazyMarvin** [comment]
Report from @tessitalisman

> Attempting to create a new entry causing the app to almost immediately exit after briefly flashing an entry box
> 
>     Open App
>     Press the "+" button
>     Get sent to Homescreen
> 
> I assume I would be able to enter some details and create a new item
> 
> See Video [here](https://drive.google.com/file/d/1hy4kgRqnXck-gzOqlMDXoyZK_wkdE2vO/view?usp=drivesdk)
> 
>     Oppo Reno f11
> 
>     OPPO CPH2603
> 
>     ColorOS_14.0_Android_14 (Security Update Oct_5)
> 
>     App Version 1.0.5
>     (Crash reproduced on GitHub, Fdroid and Google Play releases)
> 
> Note that this is upon first installation, apologies if this is a duplicate, I just wished to add extra details and was unsure if a different device model would constitute as a duplicate.

**Comment by CrazyMarvin** [comment]
May you please share Logcat logs if possible, @woodmaker, @spj2401Dev, @anantone, @dinosophos, @PedroZero, @ionlycod, @GodLokiGP, @chenshuiluke, @zekooooo & @JD-The-65th?

**Comment by chenshuiluke** [comment]
@CrazyMarvin how do I go about sharing logcat logs with you?

**Comment by ionlycod** [comment]
> @CrazyMarvin how do I go about sharing logcat logs with you?

Well first you need have Android Studio installed...

**Comment by CrazyMarvin** [comment]
Another option is to use the adb shell: `adb logcat -e "rocks.poopjournal.fucksgiven" > logcat.txt`

**Comment by CrazyMarvin** [comment]
@mubeen1519 sent some fixes (#144). Hopefully release [v1.0.6](https://github.com/Crazy-Marvin/FucksGiven/releases/tag/v1.0.6) fixes the crashes.

**Comment by JD-The-65th** [comment]
Can confirm, the app now works on my S24 and I can finally give a fuck.

**Comment by chenshuiluke** [comment]
I can now give a fuck as well

**Comment by dinosophos** [comment]
Me too, fucks are being given as we speak. thank you kindly!

**Comment by v1s7** [comment]
The crash is gone for me as well, big props to the contributor!
I guess the issue can be closed since this particular bug affecting many has been fixed in #144.

**Comment by ionlycod** [comment]
Thank you everyone for giving a fuck to this issue. 🙏🙏
